### ISSUE TITLE
Implement other movie database APIs

### ISSUE THREAD

**Issue by RenegadeFox** [RenegadeFox/movie-metadata#2]
A cool future enhancement would be the ability to use other movie database APIs, such as [tmdb](https://www.themoviedb.org/en) instead of just [omdb](https://www.omdbapi.com)

This could be done when `movie-metadata` is run for the first time, let the user decide which database API to use. The decision would then be saved to a JSON/settings file in the directory of `movie-metadata` (if globally installed) or the project directory (if locally installed).

**Comment by mcgowanjc33** [comment]
Trying to download this movie
